name: api

on:
  workflow_dispatch:

jobs:
  env_setup:
    runs-on: ubuntu-latest
    steps:
      - name: api
        uses: indiesdev/curl@v1.1
        id: api
        with:
          url: https://api.github.com/repos/bromba-noesis/envs-public/environments/Development
          method: "GET"
          accept: 200, 422
          headers: '{ "Accept": "application/vnd.github+json", "X-GitHub-Api-Version": "2022-11-28" }'
          bearer-token: ${{ secrets.BROMBA_NOESIS_PAT2 }}
          body: '{ "reviewers":[{"type":"User","id":1}] }'
          
      - name: response
        run: |
          set +x
          echo ${{ steps.api.outputs.response }} 
      
      - name: parsed_response
        run: |
          set +x
          echo '${{ fromJson(steps.api.outputs.response).status_code }}'
