name: api

on:
  workflow_dispatch:

jobs:
  env_setup:
    runs-on: ubuntu-latest
    steps:
      - name: api
        uses: indiesdev/curl@v1.1
        with:
          url: https://api.github.com/repos/bromba-noesis/envs-public/environments/Development
          method: "GET"
          accept: 200
          headers: '{ "Accept": "application/vnd.github+json" }'
          #bearer-token: ${{ secrets.BROMBA_NOESIS_PAT2 }}
          log-response: true

      - name: response
        run: echo ${{ steps.api.outputs.response }}
