name: api

on:
  workflow_dispatch:

jobs:
  repo_setup:
    runs-on: ubuntu-latest
    steps:
    
      - name: create_qua_env
        uses: indiesdev/curl@v1.1
        id: env
        with:
          url: https://api.github.com/repos/bromba-noesis/envs-public/environments/Quality
          method: "PUT"
          accept: 200, 422
          headers: '{ "Accept": "application/vnd.github+json", "X-GitHub-Api-Version": "2022-11-28" }'
          bearer-token: ${{ secrets.BROMBA_NOESIS_PAT2 }}
          body: '{ "reviewers":[{"type":"User","id":126766083}], "deployment_branch_policy":{"protected_branches":false,"custom_branch_policies":true} }'    # find user id here: https://caius.github.io/github_id/
          log-response: false
          
      - name: create_qua_env_response
        run: |
          set +x
          echo ${{ steps.create_qua_env.outputs.response }} 
      
      - name: create_qua_env_parsed_response
        run: |
          set +x
          echo '${{ fromJson(steps.create_qua_env.outputs.response).status_code }}'

      - name: limit_qua_env_branches
        uses: indiesdev/curl@v1.1
        id: env_branches
        with:
          url: https://api.github.com/repos/bromba-noesis/envs-public/environments/Quality/deployment-branch-policies
          method: "POST"
          accept: 200, 303, 404
          headers: '{ "Accept": "application/vnd.github+json", "X-GitHub-Api-Version": "2022-11-28" }'
          bearer-token: ${{ secrets.BROMBA_NOESIS_PAT2 }}
          body: '{ "name":"release/**" }'

      - name: protect_dev_branch
        uses: indiesdev/curl@v1.1
        id: branches_dev
        with:
          url: https://api.github.com/repos/bromba-noesis/envs-public/branches/development/protection
          method: "PUT"
          accept: 200, 403, 404, 422
          headers: '{ "Accept": "application/vnd.github+json", "X-GitHub-Api-Version": "2022-11-28" }'
          bearer-token: ${{ secrets.BROMBA_NOESIS_PAT2 }}
          body: '{"required_status_checks":{"strict":true,"contexts":["continuous-integration/travis-ci"]},"enforce_admins":true,"required_pull_request_reviews":{"dismissal_restrictions":{"users":["octocat"],"teams":["justice-league"]},"dismiss_stale_reviews":true,"require_code_owner_reviews":true,"required_approving_review_count":2,"require_last_push_approval":true,"bypass_pull_request_allowances":{"users":["octocat"],"teams":["justice-league"]}},"restrictions":{"users":["octocat"],"teams":["justice-league"],"apps":["super-ci"]},"required_linear_history":true,"allow_force_pushes":true,"allow_deletions":true,"block_creations":true,"required_conversation_resolution":true,"lock_branch":true,"allow_fork_syncing":true}'
          log-response: true

      - name: get_repo_id
        id: get_repo_id
        env:
          GH_TOKEN: ${{ secrets.BROMBA_NOESIS_PAT2 }}
        run: gh repo view bromba-noesis/test --json id --jq '.id'

      - name: protect_release_branches
        uses: indiesdev/curl@v1.1
        id: branches_releases
        with:
          url: https://api.github.com/graphql
          method: "POST"
          bearer-token: ${{ secrets.BROMBA_NOESIS_PAT2 }}
         #body: " \ { \ \"query\": \"query { viewer { login }}\" \ } \ " #login query
         #body: " \ { \ \"query\": \"mutation CreateRepository($repositoryInput: CreateRepositoryInput!) { createRepository(input: $repositoryInput) { repository { id name url } } } \", \"variables\": { \"repositoryInput\": { \"name\": \"xxx\", \"visibility\": \"PUBLIC\" } } \ } \ " # create repo
          body: " \ { \ \"query\": \"mutation CreateBranchProtectionRule($branchProtectionRuleInput: CreateBranchProtectionRuleInput!) { createBranchProtectionRule(input: $branchProtectionRuleInput) { branchProtectionRule  { id } } } \", \"variables\": { \"branchProtectionRuleInput\": { \"repositoryId\": \"R_kgDOKTOttg\", \"pattern\": \"release/**\" } } \ } \ "
          log-response: false
          timeout: 3000

      - name: protect_release_branches_response
        run: |
          set +x
          echo ${{ steps.protect_release_branches.outputs.response }} 
