name: calls

on: 
    workflow_dispatch:

jobs:
  get-xml-values:
    uses: bromba-noesis/workflows-repo/.github/workflows/xml_values.yml@main
    secrets: inherit

  echo-xml-values:
    runs-on: ubuntu-latest
    needs: get-xml-values
    steps:
      - name: show
        env:
          libGroup: ${{needs.get-xml-values.outputs.libGroup}}
          libArtifact: ${{needs.get-xml-values.outputs.libArtifact}}
          libVersion: ${{needs.get-xml-values.outputs.libVersion}}
        run: |
          echo "libGroup: $libGroup"
          echo "libArtifact: $libArtifact"
          echo "libVersion: $libVersion"
