name: test

on: 
    workflow_dispatch:

jobs:
  test1:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: versions 
        run: |
          Select-Xml -Path pom.xml -XPath '/project/properties/revision'
          myVar=$(Select-Xml -Path pom.xml -XPath '/project/properties/revision') >> $GITHUB_ENV

  test2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: check 
        if: ${{ hashFiles('README.md') != '' }}
        run: |
          echo README.md found!!!

      - name: versions
        id: versions
        run: |
          echo -
          #echo "myVar=$(mvn help:evaluate -Dexpression=project.properties.revision -q -DforceStdout)" >> $GITHUB_ENV
          #echo "myVar=$(mvn help:evaluate -Dexpression=project.modelVersion -q -DforceStdout)" >> $GITHUB_ENV

      - name: show
        run: echo ${{ env.myVar }}
