name: test

on: 
    workflow_dispatch:

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: check 
        if: ${{ hashFiles('README.md') != '' }}
        run: |
          echo README.md found!!!

      - name: versions
        id: versions
        run: |
          pwd
          ls -la
          echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: show
        run: echo ${{ env.RELEASE_VERSION }}
