name: test

on: 
    workflow_dispatch:

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: check 
        if: ${{ hashFiles('README.mdxx') <> '' }}
        run: |
          echo README.md found!!!

      - name: versions
        id: versions
        run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)

      - name: show
        run: echo ${{ steps.versions.outputs.version }}
