name: test

on: 
    workflow_dispatch:

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: check 
        if: ${{ hashFiles('README.mdxx') == '' }}
        run: |
          echo README.md found!!!

      - name: versions
        run: |
          echo project_version=$(mvn help:evaluate -Dexpression=./pom.xml-project.version -q -DforceStdout) >> $GITHUB_ENV
          echo ${{ GITHUB_ENV.project_version }}
