name: test

on: 
    workflow_dispatch:

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: check 
        if: ${{ hashFiles('README.mdxx') == '' }}
        run: |
          echo README.md found!!!

      - name: versions
        run: |
          VERSION=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout )
          echo "::set-output name=version::$VERSION"
