name: test

on: 
    workflow_dispatch:

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: check 
        if: ${{ hashFiles('README.md') != '' }}
        run: |
          echo README.md found!!!

      - name: versions
        id: versions
        run: |
          
          echo "myVar=$(awk -F'[><]' '/<version>/{print $3}' pom.xml)" >> $GITHUB_ENV
        
        #echo "myVar=$(mvn help:evaluate -Dexpression=project.build.extensions.extension.version -q -DforceStdout)" >> $GITHUB_ENV
        # echo "myVar=$(mvn help:evaluate -Dexpression=project.packaging -q -DforceStdout)" >> $GITHUB_ENV

      - name: show
        run: echo ${{ env.myVar }}
