name: test

on: 
    workflow_dispatch:

jobs:
  test1:
    runs-on: windows-latest
    outputs:
        libGroup-output: ${{ steps.values.outputs.libGroup }}
        libArtifact-output: ${{ steps.values.outputs.libArtifact }}
        libVersion-output: ${{ steps.values.outputs.libVersion }}
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: 'pom.xml'
    
      - name: values 
        id: values
        shell: pwsh
        run: |
          $x = [xml](gc pom.xml)

          $lgrp = $x.project.parent.groupId | fl | Out-String
          echo $lgrp

          $lart = $x.project.parent.artifactId | fl | Out-String
          echo $lart
          
          $lver = $x.project.parent.version | fl | Out-String
          echo $lver

          echo "libGroup=$lgrp" >> $Env:GITHUB_OUTPUT
          echo "libArtifact=$lart" >> $Env:GITHUB_OUTPUT
          echo "libVersion=$lver" >> $Env:GITHUB_OUTPUT

  test2:
    runs-on: ubuntu-latest
    needs: test1
    steps:
      #- uses: actions/checkout@v3
    
      #- name: check 
      #  if: ${{ hashFiles('README.md') != '' }}
      #  run: |
      #    echo README.md found!!!

      - name: show
        env:
          libGroup: ${{needs.test1.outputs.libGroup-output}}
          libArtifact: ${{needs.test1.outputs.libArtifact-output}}
          libVersion: ${{needs.test1.outputs.libVersion-output}}
        run: |
          echo "libGroup: $libGroup"
          echo "libArtifact: $libArtifact"
          echo "libVersion: $libVersion"
