name: test

on: 
    workflow_dispatch:

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: check 
        if: ${{ hashFiles('README.md') == '' }}
        run: |
          echo README.md found!!!

      - name: versions
        run: |
          mvn --version
