name: test

on: 
    workflow_dispatch:

jobs:
  test1:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: versions 
        shell: pwsh
        run: |
          $x = [xml](gc pom.xml)
          $lver = $x.project.parent.version | fl
          echo $lver
          Write-Host "libVersion=$lver" >> $GITHUB_ENV

  test2:
    runs-on: ubuntu-latest
    needs: test1
    steps:
      #- uses: actions/checkout@v3
    
      #- name: check 
      #  if: ${{ hashFiles('README.md') != '' }}
      #  run: |
      #    echo README.md found!!!

      #- name: versions
      #  id: versions
      #  run: |
      #    echo -
          #echo "myVar=$(mvn help:evaluate -Dexpression=project.properties.revision -q -DforceStdout)" >> $GITHUB_ENV
          #echo "myVar=$(mvn help:evaluate -Dexpression=project.modelVersion -q -DforceStdout)" >> $GITHUB_ENV

      - name: show
        run: echo ${{ env.libVersion }}
